spring:
  application:
    name: cadastro-usuario
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
    username: sa
    password:
